name = "DT47 Servers Cobblemon"
author = "MetalBox47"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b38f9c4fdb50b1df688149a7448daf10ed76e840fb55dd6ddd52b47c20b8aa0b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
