name = "DT47 Servers Cobblemon"
author = "MetalBox47"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "438bf02675149bda84c5e211af7ebc1f53def493bb77037e64c67028c6259c9e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
